name: api-build-provision-deploy-cli

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - food-api

trigger: none

variables:
  dotnetSdkVersion: "6.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: scConfig
  apifolder: food-api
  appservice: foodapi-staging-cli
  # envflag: app-config comes from app config

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: "AppConfig"
    jobs:    
      - job: AppConfig

        steps:
        - task: AzureAppConfiguration@5
          inputs:
            azureSubscription: 'scMI'
            AppConfigurationEndpoint: 'https://foodconfig-secure.azconfig.io'
            KeyFilter: '*'
            
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: 'echo $(envflag)'