name: api-build-deploy-cli

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - food-api

trigger: none

variables:
  dotnetSdkVersion: "6.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: az400-mod10-subscription
  apifolder: food-api
  appservice: foodapi-staging-cli
  envflag: staging

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: Build
    displayName: Build and Provision
    jobs:
      - job: Build

        steps:
          - task: UseDotNet@2
            displayName: "Use .NET Core SDK $(dotnetSdkVersion)"
            inputs:
              version: "$(dotnetSdkVersion)"

          - task: DotNetCoreCLI@2
            displayName: "Restore project dependencies"
            inputs:
              command: "restore"
              projects: "$(apifolder)/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Build the project - $(buildConfiguration)"
            inputs:
              command: "build"
              arguments: "--no-restore --configuration $(buildConfiguration)"
              projects: "$(apifolder)/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Publish the project - $(buildConfiguration)"
            inputs:
              command: "publish"
              projects: "$(apifolder)/*.csproj"
              publishWebProjects: false
              arguments: "--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)"
              zipAfterPublish: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"
      
      - job: Provision

        steps:
        
        - task: AzureCLI@2
          displayName: 'Provision AppService'
          inputs:
            azureSubscription: '$(azSubscription)'
            scriptType: 'bash'
            scriptLocation: 'scriptPath'
            scriptPath: '$(System.DefaultWorkingDirectory)/az-cli/create-api.sh'
            arguments: '$(envflag)'