name: api-template

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - food-api

trigger: none

variables:
  dotnetSdkVersion: "6.x"
  buildConfiguration: "Release"
  releaseBranchName: "master"
  apifolder: food-api
  apitestfolder: food-api-test

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: "Build"
    displayName: "Build"
    jobs:
      - job: "Build"

        steps:
          - template: templates/netcore-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(apifolder)

      - job: test_dotnet
        displayName: "Test"

        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: "test"
              projects: "apitestfolder/*.csproj"
              arguments: "--configuration $(buildConfiguration)"

