name: ng-build-deploy-cli

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - FoodUI

variables:
  azSubscription: az400-mod13-subscription
  uiPath: FoodUI/
  rndnumber: '030'
  appservice: 'foodui'
  # apiurl value will be used in FileTransform@1
  apiurl: 'https://foodapi-$(rndnumber).azurewebsites.net/'

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: Build
    displayName: Build and Provision
    jobs:
      - job: ngBuild

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: "Install Node 14"
            
          - task: FileTransform@1
            displayName: Replace Api Url
            inputs:
              folderPath: '$(System.DefaultWorkingDirectory)/**/assets'
              fileType: 'json'
              targetFiles: '**/app-config.json'

          - script: |
              npm i -g @angular/cli
              npm i
              ng b -c production
            displayName: "npm install and build"
            workingDirectory: $(uiPath)

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/$(uiPath)dist/'
              ArtifactName: 'ngapp'
      
      - job: Provision

        steps:
        
        - task: AzureCLI@2
          displayName: 'Provision AppService'
          inputs:
            azureSubscription: '$(azSubscription)'
            scriptType: 'bash'
            scriptLocation: 'scriptPath'
            scriptPath: '$(System.DefaultWorkingDirectory)/az-cli/create-ui-webapp.sh'
            arguments: '$(rndnumber)'

  - stage: Deploy
    displayName: Deploy
    dependsOn: Build

    jobs:
      - deployment: DeployAppService
        displayName: Deploy to Appservice
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    artifactName: ngapp
                    downloadPath: "$(System.DefaultWorkingDirectory)"
                                          
                - bash: ls

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appservice)"
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: '$(azSubscription)'
                    appType: 'webApp'
                    WebAppName: '$(appservice)-$(rndnumber)'
                    packageForLinux: '$(System.DefaultWorkingDirectory)/food-ui/'

